import { Inter,Poppins } from "next/font/google";
import "./globals.css";
import Sidebar from "@/content/sidebar/Sidebar";
import { AuthProvider } from "./context/AuthContext";
import ThemeProvider from "@/components/theme/ThemeProvider";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({ subsets: ["latin"],weight: ["300","400","500","600","700","800","900"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
      <ThemeProvider>
      <AuthProvider>
          <Sidebar/>
          {children}
        </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
